name: 'Terraform apply 🪲'

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'deploy/**'
  #     - '!deploy/script/**'
  workflow_dispatch:

jobs:
  terraform-apply:
    name: 'Terraform apply'
    runs-on: ubuntu-latest
    environment: Dev  # Specify the environment to access its secrets
    outputs:
      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
        working-directory: deploy/

      - name: Terraform plan
        working-directory: deploy/
        run: terraform plan -out=./tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Terraform apply
        working-directory: deploy/
        run: terraform apply -auto-approve -input=false ./tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
